import { ThumbsUp, MessageCircle, Share } from "lucide-react";

interface StatBoxProps {
  title: string;
  value: string;
}

interface ActionButtonProps {
  Icon: React.ComponentType<{ className?: string }>;
  label: string;
  stats: string;
}

const StatDivider: React.FC = () => (
  <div className="w-px h-8 md:h-[33px] bg-[#EAECEC] opacity-25" />
);

const StatBox: React.FC<StatBoxProps> = ({ title, value }) => (
  <div className="flex flex-col items-center text-center">
    <p className="text-sm md:text-xl font-bold uppercase text-white">{value}</p>
    <p className="text-[10px] md:text-xs font-medium text-[#eaecec] opacity-80">
      {title}
    </p>
  </div>
);

const ActionButton: React.FC<ActionButtonProps> = ({ Icon, label, stats }) => (
  <div className="flex flex-col items-center gap-2 md:gap-3">
    <div className="flex justify-center items-center p-2 md:p-3 rounded md:rounded-lg bg-black/[0.24] backdrop-blur-[50px]">
      <Icon className="w-3.5 h-3.5 md:w-5 md:h-5 text-white" />
    </div>
    <div className="flex flex-col items-center gap-1 md:space-y-[-4px]">
      <p className="text-xs md:text-base font-semibold text-white">{label}</p>
      <p className="text-xs font-medium text-[#eaecec] opacity-80">{stats}</p>
    </div>
  </div>
);
interface AirdropConnectedStatsProps {
  totalPoints: number;
}

const AirdropConnectedStats: React.FC<AirdropConnectedStatsProps> = ({
  totalPoints,
}) => {
  return (
    <div className="flex flex-col items-center gap-6 p-4 md:p-6 rounded-lg md:rounded-xl bg-[#181818]/50 border border-white/80 backdrop-blur-[32px] w-full max-w-3xl mx-auto">
      <div className="flex flex-col md:flex-row items-center justify-center w-full gap-6">
        <div className="flex items-center justify-center gap-3 md:gap-8 w-full">
          <StatBox title="Points Generated in Ecosystem" value="7,000" />
          <StatDivider />
          <StatBox
            title="Points Generated by Player"
            value={`${((totalPoints / 7000) * 100).toFixed(2)}% [${totalPoints}]`}
          />
        </div>
      </div>

      <div className="flex flex-row items-center justify-between md:justify-center gap-4 md:gap-8 w-full">
        <ActionButton Icon={ThumbsUp} label="Like" stats="10,000 [35%]" />
        <StatDivider />
        <ActionButton Icon={Share} label="Repost" stats="15 [35%]" />
        <StatDivider />
        <ActionButton Icon={MessageCircle} label="Comment" stats="45 [35%]" />
      </div>
    </div>
  );
};

export default AirdropConnectedStats;
