name: Deployment Workflow

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        repository: 'IronclawLabs/waa-landing'
    - name: SSH Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        command_timeout: 31m #test
        script: |
          cd /home/ubuntu/waa-landing
          git restore package.json
          git restore package-lock.json
          git pull origin main
          npm i
          npm run build
          pm2 restart waa-landing --update-env
